# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-14 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(help_text='Horario de Disponibilidad', verbose_name='Hora  de Inicio')),
                ('end_time', models.TimeField(help_text='Horario de Disponibilidad', verbose_name='Hora de Fin')),
            ],
            options={
                'verbose_name': 'Horario de Disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del Empleado', max_length=250, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Empleados',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del Insumo', max_length=250, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la Sala', max_length=250, verbose_name='Nombre')),
                ('location', models.CharField(blank=True, help_text='Ubicacion de la Sala', max_length=500, null=True, verbose_name='Ubicacion')),
                ('capacity', models.IntegerField(help_text='Capacidad de la Sala', verbose_name='Capacidad')),
                ('availability', models.ManyToManyField(to='hcmfront.Availability')),
                ('supplies', models.ManyToManyField(to='hcmfront.Input')),
            ],
            options={
                'verbose_name': 'Sala de Reuniones',
                'verbose_name_plural': 'Salas de Reuniones',
            },
        ),
        migrations.CreateModel(
            name='RequestMeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.NullBooleanField(help_text='Especifica si la peticion fue aceptada', verbose_name='Estado')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcmfront.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationMeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha de inicio de la Reservacion', verbose_name='Fecha')),
                ('start_time', models.TimeField(help_text='Horario de la Reservacion', verbose_name='Hora  de Inicio')),
                ('end_time', models.TimeField(help_text='Horario de la Reservacion', verbose_name='Hora de Fin')),
                ('amount_people', models.IntegerField(help_text='Cantidad de Personas de la Reservacion', verbose_name='Cantidad de Personas')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcmfront.Employee')),
                ('meeting_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcmfront.MeetingRoom')),
                ('supplies', models.ManyToManyField(to='hcmfront.Input')),
            ],
            options={
                'verbose_name': 'Reservacion',
                'verbose_name_plural': 'Reservaciones',
            },
        ),
        migrations.AddField(
            model_name='requestmeetingroom',
            name='reservation_meeting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hcmfront.ReservationMeetingRoom'),
        ),
    ]
